### ISSUE TITLE
Upgrading to aegir 39 and the typing issues that come with it

### ISSUE THREAD

**Issue by RonaldZielaznicki** [ipfs/js-stores#221]
## Goal:

To upgrade the repository's aegir dependency to 39.

## Context:

1. Cloned the repository with the intention of hacking on a Store for Web Extension Storage, as well as to look into ways of improving query speed for Stores.

2. Looked at https://github.com/ipfs/js-stores/pull/220 and figured it'd not hurt to fix the typing issue from the missing sinon package.

3. After updating to `aegir 39.0.7`, the linter isn't happy with many of the union types. IE. `Promise<Key> | Key`

```terminal
/pfs-js-stores/packages/datastore-core/src/keytransform.ts:31:12: Returning an awaited value that is not a promise is not allowed. [Error/@typescript-eslint/return-await]
/ipfs-js-stores/packages/datastore-core/src/keytransform.ts:35:12: Returning an awaited value that is not a promise is not allowed. [Error/@typescript-eslint/return-await]
```
for [datastore-core/src/keytransform.ts](https://github.com/ipfs/js-stores/blob/03c89590acca0c475086d12166efa3bec1e20c1c/packages/datastore-core/src/keytransform.ts#LL31C70-L31C70)

## Packages with issues:

datastore-core
interface-blockstore-tests
interface-datastore-tests

blockstore-core doesn't have issues because it doesn't use implement batch with `it-drain`.

## Possible Solutions

1. Make all the functions explicitly async. I'm not a huge fan of this one due to the additional overhead that comes with unwrapping the promises.

2. Add ignores for the offending lines in the core files. I like this idea a bit even if it makes me feel a little gross still. It might be fine as long as the implementations don't follow suit.

## Misc

There were a number of other linting issues, but those were far easier to fix with `aegir lint -f`.

**Comment by achingbrain** [comment]
Thanks for opening this issue - I'm sorry it slipped through the net.

Main has been upgraded to the latest aegir - please can you let me know if this solves your issue and you can get hacking?

**Comment by RonaldZielaznicki** [comment]
@achingbrain It does! And I've already done my hacking. I just haven't made any pull requests since it was built off a branch incompatible with main.

With the version bumped and the typing issues fixed, I'll start cleaning it up.

Much obliged for addressing this too.
