### ISSUE TITLE
Redis Stores

### ISSUE THREAD

**Issue by justin0mcateer** [ipfs/js-stores#271]
Would there be any interest here in implementations of the Blockstore and Datastore backed by Redis? I see there is an implementation in Go, which is maintained in an IPFS repo. We were in need of a Redis backed implementation in TypeScript, which we have implemented. We would like to open source these implementations and wondered whether submitting a PR here would be the best approach.

**Comment by justin0mcateer** [comment]
Bump...

**Comment by achingbrain** [comment]
Sure!  Please put a PR together - you can crib from the level implementations.
