### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ./node_modules/interface-datastore/package.json

### ISSUE THREAD

**Issue by b0tm1nd** [ipfs/js-stores#295]
Tried on Node versions 16 and 18.

https://stackblitz.com/edit/node-ds14qz?file=index.js

**Comment by achingbrain** [comment]
These modules are published as ESM, you cannot `require` them, you must use `import` instead.

Further reading - https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
