### ISSUE TITLE
Default implementation MemoryStore has bug in get().  Errors.notFoundError() isn't thrown.  map.get(key) only returns `null` if map.set(key, null).

### ISSUE THREAD

**Issue by MichaelJCole** [ipfs/js-stores#300]
Please note this code: https://github.com/ipfs/js-stores/blob/main/packages/datastore-core/src/memory.ts#L25

```
  get (key: Key): Await<Uint8Array> {
    const result = this.data.get(key.toString())

    if (result == null) {
      throw Errors.notFoundError()
    }

    return result
  }
```

When map.get() can't find a value, it returns `undefined`, so Errors.notFoundError() is not thrown unless a key is specifically map.set(key, null)

I am building a custom Datastore, and debugging startup issues.

I noticed this bug when comparing my implementation to the default implementation.

The correct behavior is not specified in:

https://ipfs.github.io/js-stores/classes/datastore_core.base.BaseDatastore.html#get
https://ipfs.github.io/js-stores/interfaces/interface_datastore.index.Datastore.html#get
https://ipfs.github.io/js-stores/interfaces/interface_store.Store.html#get

This is different than the behavior of LevelDatastore, which does throw on not found:

```
  async get(key: Key): Promise<Uint8Array> {
    logDebug('get', key.toString())
    let data
    try {
      data = await this.db.get(key.toString())
    } catch (err: any) {
      logError('get', err)
      if (err.notFound != null) {
        throw Errors.notFoundError(err)
      }

      throw Errors.dbWriteFailedError(err)
    }
    return data
  }
```
So the startup is different.
```
  backend:debug:LevelDatastore get /peers/bafzaajaiaejcbzrqadljmwftbtkuaxcvf4hwpl6mbbgjpwwzqg4b5hbsbxbh4oeg +0ms
  backend:error:LevelDatastore get [Error: NotFound: ] {
  code: 'LEVEL_NOT_FOUND',
  notFound: true,
  status: 404
} +0ms
```

So:
- Should an implementation throw or not?
- The implementations are different, which one is correct?

**Comment by MichaelJCole** [comment]
This null bug is also here, but it looks like uint8arrays/equals takes care of it:  https://github.com/libp2p/js-libp2p/blob/main/packages/peer-store/src/store.ts#L169

**Comment by MichaelJCole** [comment]
Ok, this kind of sucks but I've put at least 20 hours into this and have to move on.  I had to add a hack to make my code work.  

I'm integrating a sqlite3 database.  It has a get/setBlob interface.  sqlite3 is sync for performance reasons.  So my Datastore's functions are sync.

The problem is on startup, when my get() function throws Errors.notFoundError(), the PeerStore never put()s the Peer.  
On a MemoryStore start, the libp2p client would get/put a peer, increasing the bytes every time.

On my store, it would only get - no puts.  I think this is because #findExistingPeer doesn't return data that #saveIfDifferent wants to save.  

To fix, instead of throwing Errors.notFoundError(), I return an empty UInt8Array().  For whatever reason, the Peerstore merges the data and does puts. 
```
  get(key: Key): Uint8Array {
    try {
      const val = this.db.getBlob(this.collection, key.toString())
      logDebug('get', val?.length, key.toString())

      if (val === undefined) {
        return new Uint8Array() // <---  This works

        // Below does not :-(

        const err = Errors.notFoundError()
        logError('get', key.toString(), err.message)
        throw err
      }
      return val
    } catch (err: any) {
      console.log('err', err.code, err.message)
      throw Errors.dbReadFailedError(err)
    }
  }
  ```

I also did some logging with the LevelStore and saw that it throws, but the PeerStore seems to do puts in that case.  I don't understand it and I need to move on.

**Comment by achingbrain** [comment]
> When map.get() can't find a value, it returns undefined, so Errors.notFoundError() is not thrown unless a key is specifically map.set(key, null)

The check is:

```js
if (result == null) {
  throw Errors.notFoundError()
}
```

The `==` means `undefined == null` is `true` & there is a test for this, which passes:

https://github.com/ipfs/js-stores/blob/3d84dd0ab164fb5749c34487a217c763d1d09ccb/packages/interface-blockstore-tests/src/index.ts#L148-L161

> Should an implementation throw or not?

It should throw, as the test ensures.

> The problem is on createLibp2p, when my get() function throws Errors.notFoundError(), the PeerStore never put()s the Peer.

This sounds like something else - please can you open an issue against libp2p with a repro case?
