### ISSUE TITLE
README.md repeated narrative

### ISSUE THREAD

**Issue by D7x7z49** [ipfs/js-stores#307]
look -> https://github.com/ipfs/js-stores

![image](https://github.com/ipfs/js-stores/assets/85430783/ed8947f3-fa9a-4a96-b8d4-61122c30ea5d)

**Comment by achingbrain** [comment]
I'm not sure what this issue is reporting?  The modules in the list all do different things, none of the entries are duplicated and they are sorted in alphabetical order.
