### ISSUE TITLE
multiformat encoding benchmarks in blockstore-fs

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-stores#313]
https://github.com/ipfs/js-stores/tree/main/packages/blockstore-fs/benchmarks/encoding

Was looking for blockstore/datastore benchmarks and found these. Do these belong here?

**Comment by achingbrain** [comment]
On the face of it probably not, but they were added to ensure that when [encoding](https://github.com/ipfs/js-stores/blob/main/packages/blockstore-fs/src/sharding.ts#L100) a multihash into a fs path, we didn't accidentally pick a really slow algorithm.
